### ISSUE TITLE
1.0.1.0 release planning

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/base64-bytestring#28]
I propose to cut the next minor release once the fixes for #18 (for which there's a PR) and #24 (which @hvr is working on - his patch actually has a bit bigger scope than described in that ticket) are merged.

Since there will be API additions, version number should be 1.0.1.0.

**Comment by 23Skidoo** [comment]
#26 merged, version bumped in `master`.

**Comment by emilypi** [comment]
@23Skidoo just as a head's up, I found a bug with the way we're padding out unpadded bytestrings. I'll have a PR out tomorrow addressing the error.

**Comment by emilypi** [comment]
@23Skidoo @hvr See #30

**Comment by emilypi** [comment]
All done, and released under 1.1.0.0 😄
