### ISSUE TITLE
disable padding for Base64.URL?

### ISSUE THREAD

**Issue by GildedHonour** [haskell/base64-bytestring#29]
How can I disable padding in the fuction `encode` of `Data.ByteString.Base64.URL`?

**Comment by emilypi** [comment]
Hi @GildedHonour - 

It hasn't been released yet, but the next version of `base64-bytestring` will include a `encodeUnpadded` primitive for URL-safe alphabets that will get you precisely what you need.


This will be available once https://github.com/haskell/base64-bytestring/issues/28 is finished.

**Comment by 23Skidoo** [comment]
Closing in favour of #28.
