### ISSUE TITLE
Fails When String Includes Byte Order Mark

### ISSUE THREAD

**Issue by devinlyons** [haskell/base64-bytestring#42]
I'm working with an app where users are expected to upload a CSV file. When the file contains a BOM, decoding the base64 string fails. This example base64 string includes a byte order mark: `77u/SGVhZGVyIDEsSGVhZGVyIDIsSGVhZGVyIDMNCkRhdGEgMS4xLERhdGEgMS4yLERhdGEgMS4zDQpEYXRhIDIuMSxEYXRhIDIuMixEYXRhIDIuMw0K`. The data should look like this:

``` csv
﻿Header 1,Header 2,Header 3
Data 1.1,Data 1.2,Data 1.3
Data 2.1,Data 2.2,Data 2.3
```

But when I try to decode it, I get this result: `Left "invalid character at offset: 3"`.
If I try to decode it without the BOM, it works.

**Comment by emilypi** [comment]
I can decode this just fine: 

```haskell
П> Data.ByteString.Base64.decode "77u/SGVhZGVyIDEsSGVhZGVyIDIsSGVhZGVyIDMNCkRhdGEgMS4xLERhdGEgMS4yLERhdGEgMS4zDQpEYXRhIDIuMSxEYXRhIDIuMixEYXRhIDIuMw0K"
Right "\239\187\191Header 1,Header 2,Header 3\r\nData 1.1,Data 1.2,Data 1.3\r\nData 2.1,Data 2.2,Data 2.3\r\n"
```

It shows the BOM is `\239\187\191`. I can match your error if i decode it as Base64 URL: 

```haskell
П> Data.ByteString.Base64.URL.decode "77u/SGVhZGVyIDEsSGVhZGVyIDIsSGVhZGVyIDMNCkRhdGEgMS4xLERhdGEgMS4yLERhdGEgMS4zDQpEYXRhIDIuMSxEYXRhIDIuMixEYXRhIDIuMw0K"
Left "invalid character at offset: 3"
```

Is this a problem of unexpected base64 encoding alphabet?

**Comment by emilypi** [comment]
Actually, now that I stare at the string, I'm almost certain this is an alphabet mismatch issue on your part. The substring "77u/" is most definitely not URL-safe.
